// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.13.0
// source: test.proto

package test

import (
	_ "github.com/driftingboy/protoc-gen-go-errors/gerr"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestErrorReason int32

const (
	TestErrorReason_TestNotFound TestErrorReason = 0
	TestErrorReason_TestBusy     TestErrorReason = 1
	TestErrorReason_TestIncrease TestErrorReason = 2
	TestErrorReason_TestRedirect TestErrorReason = 3
)

// Enum value maps for TestErrorReason.
var (
	TestErrorReason_name = map[int32]string{
		0: "TestNotFound",
		1: "TestBusy",
		2: "TestIncrease",
		3: "TestRedirect",
	}
	TestErrorReason_value = map[string]int32{
		"TestNotFound": 0,
		"TestBusy":     1,
		"TestIncrease": 2,
		"TestRedirect": 3,
	}
)

func (x TestErrorReason) Enum() *TestErrorReason {
	p := new(TestErrorReason)
	*p = x
	return p
}

func (x TestErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (TestErrorReason) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x TestErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestErrorReason.Descriptor instead.
func (TestErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x7d, 0x0a, 0x0f, 0x54, 0x65, 0x73, 0x74, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x0c, 0x54, 0x65,
	0x73, 0x74, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x00, 0x1a, 0x06, 0xaa, 0x45,
	0x03, 0x08, 0x94, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x42, 0x75, 0x73, 0x79,
	0x10, 0x01, 0x12, 0x1c, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61,
	0x73, 0x65, 0x10, 0x02, 0x1a, 0x0a, 0xaa, 0x45, 0x07, 0x08, 0xf6, 0x03, 0x10, 0xaa, 0x8d, 0x06,
	0x12, 0x18, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x10, 0x03, 0x1a, 0x06, 0xaa, 0x45, 0x03, 0x08, 0xae, 0x02, 0x1a, 0x0a, 0xa2, 0x45, 0x07, 0x08,
	0xf4, 0x03, 0x10, 0xa1, 0x8d, 0x06, 0x42, 0x12, 0x5a, 0x10, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_goTypes = []interface{}{
	(TestErrorReason)(0), // 0: errors.test.TestErrorReason
}
var file_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
