// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package test

import (
	fmt "fmt"
	errors "github.com/driftingboy/protoc-gen-go-errors/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

var bizErrorCodeMap map[string]int = map[string]int{

	"errors.test_TestErrorReason_TestNotFound": 100001,
}

func IsTestnotfound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == "errors.test_TestErrorReason_TestNotFound" && e.Code == 404
}

func ErrorTestnotfound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, "errors.test_TestErrorReason_TestNotFound", fmt.Sprintf(format, args...))
}

func BizErrorCode(err error) int {
	if err == nil {
		return 0
	}
	e := errors.FromError(err)
	return bizErrorCodeMap[e.Reason]
}
